name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  backend:
    name: Backend (ruff/black/pytest/mypy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn[standard] starlette
          pip install pytest ruff black mypy

      - name: Ruff (lint)
        working-directory: backend
        run: ruff check .

      - name: Black (format check)
        working-directory: backend
        run: black --check .

      - name: Pytest
        working-directory: backend
        run: pytest -q

      - name: Mypy (types)
        working-directory: backend
        run: mypy backend/app backend/tests
